version: "3.9"

services:
  ML4Earth:
    # custom docker image build on the fly
    #build:
    #  context:    /path/to/source/dir/
    #  dockerfile: /path/to/custom-Dockerfile/relative/tocontextdir/Dockerfile
    image: nvcr.io/nvidia/pytorch:23.03-py3
    working_dir: /app
    command: tail -f /dev/null
    shm_size: 2gb
    ports:
      - "8888:8888"
    hostname: localhost
    domainname: localhost
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./
        target: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 

networks:
  default:
    name: ml4earth_network
volumes:
  data:
    name: ml4earth_data
